<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colegio [
    <!ELEMENT colegio (alumnos, profesores)>
    <!ELEMENT alumnos (alumno+)>
    <!ELEMENT alumno (nombre,apellido,matricula,activo?)>
    <!ATTLIST alumno expediente CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)>
    <!ELEMENT activo EMPTY>
    <!ELEMENT profesores (profesor+)>
    <!ELEMENT profesor (nombre,curso,foto)>
    <!ELEMENT curso (#PCDATA)>
    <!ELEMENT foto (#PCDATA)>
]>
<colegio>
    <alumnos>
        <alumno expediente="AA01">
            <nombre>Marc</nombre>
            <apellido>Venteo</apellido>
            <matricula>ASIX</matricula>
            <activo />
        </alumno>
        <alumno expediente="AA02">
            <nombre>Ana</nombre>
            <apellido>Venteo</apellido>
            <matricula>ASIX</matricula>
        </alumno>
    </alumnos>
    <profesores>
        <profesor>
            <nombre>Juan</nombre>
            <curso>DAW</curso>
            <foto>Juan.jpg</foto>
        </profesor>
    </profesores>
</colegio>