<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos [
    <!ELEMENT pedidos (pedido)>
    <!ELEMENT pedido (cliente,contenido,fecha)>
    <!ELEMENT cliente (nombre,direccion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT direccion (calle,numero,piso,letra)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT piso (#PCDATA)>
    <!ELEMENT letra (#PCDATA)>
    <!ELEMENT contenido (#PCDATA)>
    <!ATTLIST contenido modelo CDATA #IMPLIED>
    <!ELEMENT fecha ((dia,mes,anno)|(anno,mes,dia))>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anno (#PCDATA)>
]>
<pedidos>
    <pedido>
        <cliente>
            <nombre>Juan Delgado Mart√≠nez</nombre>
            <direccion>
                <calle>Barco</calle>
                <numero>4</numero>
                <piso>Tercero</piso>
                <letra>A</letra>
            </direccion>
        </cliente>
        <contenido modelo="A2023">Bicicleta</contenido>
        <fecha>
            <dia>19</dia>
            <mes>05</mes>
            <anno>2000</anno>
        </fecha>
    </pedido>
</pedidos>